development:
  adapter: postgresql
  database: obvious_data_development
  encoding: unicode
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  database: obvious_data_test
  username: postgres
  password:

production:
  adapter: postgresql
  database: dummy_production
  pool: 5
  username: postgres
  password:
