name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PG_VERSION: 11
    strategy:
      matrix:
        ruby-version: [2.4.1]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install Postgres pkgs
        run: sudo apt-get install postgresql-client-$PG_VERSION postgresql-server-dev-$PG_VERSION setup
      - name: setup pg_dump
        run: setup pg_dump
      - name: ls
        run: ls -al /usr/lib/postgresql/
      - name: ln
        run: sudo ln -sfn /usr/lib/postgresql/$PG_VERSION/bin/pg_dump /usr/bin/pg_dump
      - name: restart postgres
        run: |
          sudo -E sh -c 'service postgresql stop'
          sleep 5s
          sudo -E sh -c 'service postgresql start $PG_VERSION'
      - name: verify postgres
        run: psql -U postgres -d postgres -c 'select setting from pg_settings where name = $m$server_version$m$;'
      - name: Install Gems
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
