name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.4.1]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: trust all postgres connections
        run: |
          sudo -E sh -c 'echo "local all postgres trust" >> /etc/postgresql/13/main/pg_hba.conf'
          sudo cat /etc/postgresql/13/main/pg_hba.conf
      - name: restart postgres
        run: |
          sudo -E sh -c 'service postgresql stop'
          sleep 5s
          sudo -E sh -c 'service postgresql start 13'
      - name: Install Gems
        run: bundle install
      - name: Run tests
        run: |
          bundle exec rake app:db:test:prepare
          bundle exec rspec
